name: Deploy

on:
  workflow_dispatch:

jobs:
  deploy:
    name: "Deployment"
    runs-on: ubuntu-latest
    environment: prd
    steps:
      - name: "Init => Run checkout@v2"
        run:             |
          eval $(ssh-agent -s)
          ssh-add - <<< "${MY_SECRET_KEY}"
          ssh -o StrictHostKeyChecking=no red@red.pdm.ovh docker pull ghcr.io/altamos/cv:latest
          ssh -o StrictHostKeyChecking=no red@red.pdm.ovh docker stop cv || true
          ssh -o StrictHostKeyChecking=no red@red.pdm.ovh docker run --rm -dti -p 80:80 --name cv ghcr.io/altamos/cv:latest
        env:
          MY_SECRET_KEY: ${{ secrets.ENCRYPTED_SSH_KEY }}
